version: '3'
services: 
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # image: "grafana/grafana:${TAG_GRAFANA}"
    ports: 
      - "3001:3000"
    container_name: grafana
    restart: unless-stopped
    # volumes: #make the volumes persitent
    #   - ./data/grafana:/var/lib/grafana
    environment: # hide the secrets -- using secrets manager or github secrets
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSGRAFANA
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=myrul.com
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=myemail@gmail.com
      - GF_SMTP_PASSWORD=mypassword
      - GF_SMTP_FROM_ADDRESS=myemail@gmail.com
