version: '3'
services: 
  grafana:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: "grafana/grafana:${TAG_GRAFANA}"
    ports: 
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    # volumes: #make the volumes persitent
    #   - ./data/grafana:/var/lib/grafana
    environment: # hide the secrets -- using secrets manager or github secrets
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=${GF_SERVER_DOMAIN}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${GF_SMTP_HOST}
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS}
