name: 'Deploy CloudFormation Stack - Beanstalk,S3' # S3, CF Stack
on:
  push:
    branches:
    - master
    pull_request:

jobs:
  beanstalk:
    name: Deploy Beanstalk Env
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        # aws-region: ${{ github.event.inputs.region }}

    # - name: Set envs
    #     Set envs like: stack version, beanstalk env to update

    # - name: Verify if bucket exist

    - name: zip the dockerfile and docker-compose
      working-directory: ./docker
      run: zip -r deploy.zip *

    - name: Create S3 Bucket for the first time
      working-directory: ./docker
      run: aws s3 mb s3://eb-test-jsanchez --region us-east-1

    - name: Copy .zip dockerfile to S3 bucket
      working-directory: ./docker
      run: aws s3 sync deploy.zip s3://eb-test-jsanchez
      # !!! Add new feature::: No syncing if file exist

    - name: Deploy Stack CF
      id: beanstalk-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: beanstalk-jsanchez-stack-ga
        template: beanstalk-ga.yaml
        no-fail-on-empty-changeset: "1"
        # parameter-overrides: "env-bean"